name: faro
version: 0.0.1.0
synopsis: Linter for nixpkgs
description: See README at https://git.sr.ht/~kaction/faro
author: Dmitry Bogatov
category: Distribution
license: BSD-3-Clause

dependencies:
  - base
  - containers
  - data-fix
  - hnix
  - mtl
  - optparse-applicative
  - text
  - prettyprinter

executables:
  faro:
    main: Main.hs
    dependencies:
      - base
      - faro

library:
  source-dirs: src

tests:
  faro-test:
    source-dirs: test
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - faro
      - hedgehog
